###
### BEFORE RUNNING

# DEV SETTINGS:
### nuxt.config.js
#       baseURL: 'http://127.0.0.1:5000',
#       https: false,

### .env file
#       API_PORT=5000

# PROD SETTINGS:
### nuxt.config.js
#       baseURL: 'https://api.tax-automation.com',
#       https: false # at the moment false, later --> #true,

### .env file
#       API_PORT=80
###

version: '3'

services:

    nuxt:
        container_name: nuxt
        build:
            context: ./nuxt
            dockerfile: Dockerfile
            args:
                - NODE_VERSION=${NODE_VERSION}
        image: ${OWNER_NAME}/nuxt:${VERSION_NUMBER}
        restart: always
        expose: # EXPOSE only opens up a port within a docker network, while PORTS allows access from the outside world (the internet)
            - "3000"
        environment:
            - HOST=0.0.0.0 #provides full external access to the nuxt container on server
        depends_on:
            - api
        networks:
            - web
        command: "npm run start"

    api:
        container_name: api
        build:
            context: ./api
            dockerfile: Dockerfile
            args:
                - PYTHON_VERSION=${PYTHON_VERSION}
        image: ${OWNER_NAME}/api:${VERSION_NUMBER}
        restart: always
        expose:
            - ${API_PORT}
        depends_on: # depends_on defines the order in which the services are started
            - postgres
        networks:
            - internal
            - web
        command: gunicorn --bind 0.0.0.0:${API_PORT} wsgi:app

    postgres:
        container_name: postgres
        build:
            context: ./db
            dockerfile: Dockerfile
            args:
                - POSTGRES_VERSION=${POSTGRES_VERSION}
        image: ${OWNER_NAME}/postgres:${VERSION_NUMBER}
        restart: always
        expose:
            - "5432"
        volumes:
            - pgdata:/var/lib/postgresql/data/
        networks:
            - internal

volumes:
    pgdata:

networks:
    internal:
    web:
#         # external:
#         #     name: nginx_web
