version: '3'

services:
    proxy:
        container_name: proxy
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: ${OWNER_NAME}/proxy:${VERSION_NUMBER}
        restart: unless-stopped
        ports:
            - 5000:5000
            - 80:3000
        volumes:
            - ./nginx/dev:/etc/nginx/conf.d
        networks:
            - web
        depends_on:
            - api
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

    api:
        env_file:
            - .dev.env

    nuxt:
        env_file:
            - .dev.env


    postgres:
        env_file:
            - .dev.env


networks:
    internal:
    web:
