version: '3'

services:

    proxy:
        container_name: proxy
        build:
            context: ./nginx
            dockerfile: Dockerfile
            args:
                - NGINX_VERSION=${NGINX_VERSION}
                - ENVIRONMENT=dev
        image: ${OWNER_NAME}/proxy:${VERSION_NUMBER}
        restart: unless-stopped
        # volumes:
        #       - media_data:/var/lib/media_data:ro
        ports:
            - 5000:5000
            - 80:80
        networks:
            - web
        depends_on:
            - api

        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
        # improved version based on: https://stackoverflow.com/questions/57554703/why-use-nginx-with-daemon-off-in-background-with-docker
        #command: '/bin/sh -c ''while :; do sleep 6h; nginx -s reload; done & exec nginx -g "daemon off;"'''


    rabbitmq:
        env_file:
            - .dev.env

    celery-worker:
        env_file:
            - .dev.env




    api:
        volumes:
              - ./api/migrations/:/home/api/migrations
        env_file:
            - .dev.env
        #command: bash -c "./wait-for-it.sh postgres:5432 --timeout=2 && flask run --host 0.0.0.0 --port 5000"


    # front:
    #     build:
    #         context: ./front
    #         dockerfile: Dockerfile.dev
    #         args:
    #             - NODE_VERSION=${NODE_VERSION}
    #     env_file:
    #         - .dev.env
    #     command: "npm run dev"

    postgres:
        environment:
            - DATABASE=postgres
        ports:
            - 5432:5432
        env_file:
            - .dev.env
