version: '3'

services:
    api:
        environment:
            - FLASK_ENV=dev
        command: ['gunicorn', '-w', '1', '--bind', '0.0.0.0:5000', 'wsgi:app']


    postgres:
        ports:
            - "5432:5432"

    nuxt:
        ports:
            - "3000:3000"
