branch-defaults:
  traeffic_integration:
    environment: prod
    group_suffix: null
global:
  application_name: tax-automation-beta
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
