from typing import List
from mypy_extensions import TypedDict
from datetime import date, datetime

class TransactionInputInterface(TypedDict, total=False):
    original_filename: str
    created_on: datetime
    created_by: int

    processed: bool
    processed_on: datetime
    transactions: List['app.namepsaces.transaction.Transaction']
    notifications: List['app.namepsaces.utils.Notification']

    account_given_id: str
    public_activity_period: str
    channel_code: str
    marketplace: str
    transaction_type_public_code: str
    given_id: str
    activity_id: str
    shipment_date: date
    arrival_date: date
    complete_date: date
    item_sku: str
    item_name: str
    item_manufacture_country: str
    item_quantity: int
    item_weight_kg: float
    item_weight_kg_total: float
    item_price_discount_gross: float
    item_price_gross: float
    item_price_total_gross: float
    shipment_price_discount_gross: float
    shipment_price_gross: float
    shipment_price_total_gross: float
    sale_total_value_gross: float
    gift_wrap_price_discount_gross: float
    gift_wrap_price_gross: float
    gift_wrap_price_total_gross: float
    currency_code: str
    departure_country_code: str
    departure_postal_code: str
    departure_city: str
    arrival_country_code: str
    arrival_postal_code: str
    arrival_city: str
    arrival_address: str
    shipment_mode: str
    shipment_conditions: str
    invoice_number: str
    invoice_url: str
    customer_name: str
    customer_vat_number: str
    customer_vat_number_country_code: str
    supplier_vat_number: str
    supplier_name: str

    # the values below are mainly used as a reference
    tax_calculation_date: date
    unit_cost_price_net: str
    item_price_discount_net: str
    item_price_discount_vat: str
    item_price_net: str
    item_price_vat: str
    item_price_total_net: str
    item_price_total_vat: str
    item_price_vat_rate: str
    shipment_price_discount_net: str
    shipment_price_discount_vat: str
    shipment_price_net: str
    shipment_price_vat: str
    shipment_price_total_net: str
    shipment_price_total_vat: str
    shipment_price_vat_rate: str
    sale_total_value_net: str
    sale_total_value_vat: str
    gift_wrap_price_discount_net: str
    gift_wrap_price_discount_vat: str
    gift_wrap_price_net: str
    gift_wrap_price_vat: str
    gift_wrap_price_total_net: str
    gift_wrap_price_total_vat: str
    gift_wrap_price_tax_rate: str
    item_given_tax_code_code: str
    departure_seller_vat_country_code: str
    departure_seller_vat_number: str
    arrival_seller_vat_country_code: str
    arrival_seller_vat_number: str
    seller_vat_country_code: str
    seller_vat_number: str
    tax_calculation_imputation_country: str
    tax_jurisdiction: str
    tax_jurisdiction_level: str
    invoice_amount_vat: str
    invoice_currency_code: str
    invoice_exchange_rate: str
    invoice_exchange_rate_date: date
    export: bool
