version: '3'

services:

  proxy:
    container_name: proxy
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./prod:/etc/nginx/conf.d
      - ./prod/certbot/conf:/etc/letsencrypt
      - ./prod/certbot/www:/var/www/certbot
    networks:
      - web
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: always
    volumes:
      - ./prod/certbot/conf:/etc/letsencrypt
      - ./prod/certbot/www:/var/www/certbot
    networks:
      - web
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # This will check if your certificate is up for renewal every 12 hours as recommended by Let’s Encrypt. see: https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
networks:
  web:
    external:
      name: nginx_web

# regarding volumes: two shared ('proxy' and 'certbot') Docker volumes. One for the validation challenges, the other for the actual certificates
