from flask_restx import Model, fields

transaction_type_dto = Model('transaction_type', {
    'code': fields.String,
    'description': fields.String
})

transaction_dto = Model('transaction', {
    'id': fields.Integer(readonly=True),
    'created_on': fields.DateTime,
    'transaction_input_id': fields.Integer,
    'account_id': fields.Integer,
    'item_id': fields.Integer,
    'amazon_vat_calculation_service': fields.Boolean,
    'customer_relationship_checked': fields.Boolean,
    'customer_relationship': fields.String,
    'customer_firm_id': fields.Integer,
    'customer_firm_vatin_id': fields.Integer,
    'tax_jurisdiction_code': fields.String,
    'type_code': fields.String,
    'tax_treatment_code': fields.String,
    'tax_date': fields.Date,
    'tax_calculation_date': fields.Date,
    'item_tax_code_code': fields.String,
    'item_tax_rate_type_code': fields.String,
    'shipment_tax_rate_type_code': fields.String,
    'gift_wrap_tax_rate_type_code': fields.String,
    'item_price_net': fields.Float,
    'item_price_discount_net': fields.Float,
    'item_price_total_net': fields.Float,
    'shipment_price_net': fields.Float,
    'shipment_price_discount_net': fields.Float,
    'shipment_price_total_net': fields.Float,
    'gift_wrap_price_net': fields.Float,
    'gift_wrap_price_discount_net': fields.Float,
    'gift_wrap_price_total_net': fields.Float,
    'item_price_vat_rate': fields.Float,
    'item_price_vat': fields.Float,
    'item_price_discount_vat': fields.Float,
    'item_price_total_vat': fields.Float,
    'shipment_price_vat_rate': fields.Float,
    'shipment_price_vat': fields.Float,
    'shipment_price_discount_vat': fields.Float,
    'shipment_price_total_vat': fields.Float,
    'gift_wrap_vat_rate': fields.Float,
    'gift_wrap_price_vat': fields.Float,
    'gift_wrap_price_discount_vat': fields.Float,
    'gift_wrap_price_total_vat': fields.Float,
    'total_value_net': fields.Float,
    'total_value_vat': fields.Float,
    'total_value_gross': fields.Float,
    'transaction_currency_code': fields.String,
    'invoice_currency_code': fields.String,
    'invoice_exchange_rate_date': fields.Date,
    'invoice_exchange_rate': fields.Float,
    'invoice_amount_net': fields.Float,
    'invoice_amount_vat': fields.Float,
    'invoice_amount_gross': fields.Float,
    'vat_rate_reverse_charge': fields.Float,
    'invoice_amount_vat_reverse_charge': fields.Float,
    'arrival_seller_vatin_id': fields.Integer,
    'departure_seller_vatin_id': fields.Integer,
    'seller_vatin_id': fields.Integer
})
