"""delete tax_record downloaded by users

Revision ID: 241cdedc0a02
Revises: 3aa7a34a9f6d
Create Date: 2020-08-01 09:00:35.276275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241cdedc0a02'
down_revision = '3aa7a34a9f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_record_user_AT')
    op.drop_constraint('tax_auditor_seller_firm_AT_tax_auditor_id_fkey', 'tax_auditor_seller_firm_AT', type_='foreignkey')
    op.drop_constraint('tax_auditor_seller_firm_AT_seller_firm_id_fkey', 'tax_auditor_seller_firm_AT', type_='foreignkey')
    op.create_foreign_key(None, 'tax_auditor_seller_firm_AT', 'user', ['tax_auditor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tax_auditor_seller_firm_AT', 'business', ['seller_firm_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tax_record_filename_key', 'tax_record', type_='unique')
    op.drop_column('tax_record', 'filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_record', sa.Column('filename', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.create_unique_constraint('tax_record_filename_key', 'tax_record', ['filename'])
    op.drop_constraint(None, 'tax_auditor_seller_firm_AT', type_='foreignkey')
    op.drop_constraint(None, 'tax_auditor_seller_firm_AT', type_='foreignkey')
    op.create_foreign_key('tax_auditor_seller_firm_AT_seller_firm_id_fkey', 'tax_auditor_seller_firm_AT', 'business', ['seller_firm_id'], ['id'])
    op.create_foreign_key('tax_auditor_seller_firm_AT_tax_auditor_id_fkey', 'tax_auditor_seller_firm_AT', 'user', ['tax_auditor_id'], ['id'])
    op.create_table('tax_record_user_AT',
    sa.Column('tax_record_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tax_record_id'], ['tax_record.id'], name='tax_record_user_AT_tax_record_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='tax_record_user_AT_user_id_fkey'),
    sa.PrimaryKeyConstraint('tax_record_id', 'user_id', name='tax_record_user_AT_pkey')
    )
    # ### end Alembic commands ###
