"""transaction without item.id and account.id

Revision ID: 31e0d9172b46
Revises: 
Create Date: 2020-07-22 15:04:39.774684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e0d9172b46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_account_id_fkey', 'transaction', type_='foreignkey')
    op.drop_constraint('transaction_item_id_fkey', 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'item_id')
    op.drop_column('transaction', 'account_id')
    op.drop_constraint('transaction_input_currency_code_fkey', 'transaction_input', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('transaction_input_currency_code_fkey', 'transaction_input', 'currency', ['currency_code'], ['code'])
    op.add_column('transaction', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transaction', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('transaction_item_id_fkey', 'transaction', 'item', ['item_id'], ['id'])
    op.create_foreign_key('transaction_account_id_fkey', 'transaction', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###
