"""relationships in transaction

Revision ID: 38900e60c2b9
Revises: 58d1acaa4ed1
Create Date: 2020-07-27 06:27:50.360816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38900e60c2b9'
down_revision = '58d1acaa4ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_auditor_seller_firm_AT')
    op.add_column('transaction', sa.Column('item_id', sa.Integer(), nullable=False))
    op.add_column('transaction', sa.Column('seller_firm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'business', ['seller_firm_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'item', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'seller_firm_id')
    op.drop_column('transaction', 'item_id')
    op.create_table('tax_auditor_seller_firm_AT',
    sa.Column('tax_auditor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seller_firm_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['seller_firm_id'], ['business.id'], name='tax_auditor_seller_firm_AT_seller_firm_id_fkey'),
    sa.ForeignKeyConstraint(['tax_auditor_id'], ['user.id'], name='tax_auditor_seller_firm_AT_tax_auditor_id_fkey'),
    sa.PrimaryKeyConstraint('tax_auditor_id', 'seller_firm_id', name='tax_auditor_seller_firm_AT_pkey')
    )
    # ### end Alembic commands ###
