"""add seller_firm_id to transaction_input

Revision ID: 42e8ecf2aa4b
Revises: 
Create Date: 2020-08-09 07:23:32.620682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e8ecf2aa4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_record', sa.Column('_intra_community_acquisitions_acquisitions_invoice_amount_vat_reverse_charge', sa.Integer(), nullable=True))
    op.add_column('tax_record', sa.Column('_intra_community_acquisitions_refunds_invoice_amount_vat_reverse_charge', sa.Integer(), nullable=True))
    op.add_column('tax_record', sa.Column('_intra_community_acquisitions_total_invoice_amount_vat_reverse_charge', sa.Integer(), nullable=True))
    op.drop_column('tax_record', '_intra_community_acquisitions_total_invoice_amount_vat_reverse_')
    op.drop_column('tax_record', '_intra_community_acquisitions_acquisitions_invoice_amount_vat_r')
    op.drop_column('tax_record', '_intra_community_acquisitions_refunds_invoice_amount_vat_revers')
    op.add_column('transaction_input', sa.Column('seller_firm_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transaction_input', 'business', ['seller_firm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_input', type_='foreignkey')
    op.drop_column('transaction_input', 'seller_firm_id')
    op.add_column('tax_record', sa.Column('_intra_community_acquisitions_refunds_invoice_amount_vat_revers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tax_record', sa.Column('_intra_community_acquisitions_acquisitions_invoice_amount_vat_r', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tax_record', sa.Column('_intra_community_acquisitions_total_invoice_amount_vat_reverse_', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tax_record', '_intra_community_acquisitions_total_invoice_amount_vat_reverse_charge')
    op.drop_column('tax_record', '_intra_community_acquisitions_refunds_invoice_amount_vat_reverse_charge')
    op.drop_column('tax_record', '_intra_community_acquisitions_acquisitions_invoice_amount_vat_reverse_charge')
    # ### end Alembic commands ###
