"""remove platform from distance sales

Revision ID: 58d1acaa4ed1
Revises: 8efb0b5a538f
Create Date: 2020-07-25 08:17:51.393234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d1acaa4ed1'
down_revision = '8efb0b5a538f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('distance_sale_platform_code_fkey', 'distance_sale', type_='foreignkey')
    op.drop_column('distance_sale', 'platform_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distance_sale', sa.Column('platform_code', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.create_foreign_key('distance_sale_platform_code_fkey', 'distance_sale', 'platform', ['platform_code'], ['code'])
    # ### end Alembic commands ###
