"""transaction input add features

Revision ID: 64f670c9c0f0
Revises: 31e0d9172b46
Create Date: 2020-07-23 16:02:15.813755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64f670c9c0f0'
down_revision = '31e0d9172b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'transaction_input', 'country', ['arrival_country_code'], ['code'])
    op.create_foreign_key(None, 'transaction_input', 'currency', ['currency_code'], ['code'])
    op.create_foreign_key(None, 'transaction_input', 'country', ['departure_country_code'], ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_input', type_='foreignkey')
    op.drop_constraint(None, 'transaction_input', type_='foreignkey')
    op.drop_constraint(None, 'transaction_input', type_='foreignkey')
    op.drop_column('notification', 'public_id')
    # ### end Alembic commands ###
