"""move notifications to transactions

Revision ID: 8efb0b5a538f
Revises: 64f670c9c0f0
Create Date: 2020-07-24 10:59:51.657619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efb0b5a538f'
down_revision = '64f670c9c0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('calculated_value', sa.String(length=256), nullable=True))
    op.add_column('notification', sa.Column('reference_value', sa.String(length=256), nullable=True))
    op.add_column('notification', sa.Column('transaction_id', sa.Integer(), nullable=False))
    op.drop_constraint('notification_transaction_input_id_fkey', 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'transaction', ['transaction_id'], ['id'])
    op.drop_column('notification', 'transaction_input_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('transaction_input_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key('notification_transaction_input_id_fkey', 'notification', 'transaction_input', ['transaction_input_id'], ['id'])
    op.drop_column('notification', 'transaction_id')
    op.drop_column('notification', 'reference_value')
    op.drop_column('notification', 'calculated_value')
    # ### end Alembic commands ###
