"""tax record add total values

Revision ID: bc7cf23cecb9
Revises: fdb3cca69407
Create Date: 2020-08-01 10:41:28.796098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7cf23cecb9'
down_revision = 'fdb3cca69407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_record', sa.Column('_total_distance_sale', sa.Integer(), nullable=True))
    op.add_column('tax_record', sa.Column('_total_export', sa.Integer(), nullable=True))
    op.add_column('tax_record', sa.Column('_total_import', sa.Integer(), nullable=True))
    op.add_column('tax_record', sa.Column('_total_intra_community_acquisition', sa.Integer(), nullable=True))
    op.add_column('tax_record', sa.Column('_total_intra_community_sale', sa.Integer(), nullable=True))
    op.add_column('tax_record', sa.Column('_total_local_acquisition', sa.Integer(), nullable=True))
    op.add_column('tax_record', sa.Column('_total_local_sale', sa.Integer(), nullable=True))
    op.add_column('tax_record', sa.Column('_total_local_sale_reverse_charge', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_record', '_total_local_sale_reverse_charge')
    op.drop_column('tax_record', '_total_local_sale')
    op.drop_column('tax_record', '_total_local_acquisition')
    op.drop_column('tax_record', '_total_intra_community_sale')
    op.drop_column('tax_record', '_total_intra_community_acquisition')
    op.drop_column('tax_record', '_total_import')
    op.drop_column('tax_record', '_total_export')
    op.drop_column('tax_record', '_total_distance_sale')
    # ### end Alembic commands ###
