"""test gone

Revision ID: c2c7ca27aac5
Revises: 71cbf070176c
Create Date: 2020-10-26 13:34:24.079857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c7ca27aac5'
down_revision = '71cbf070176c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distance_sale', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distance_sale', sa.Column('test', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
